name: Create a release version
on:
    workflow_dispatch:

jobs:
  release_draft:
    runs-on: ubuntu-latest
    steps:
    - name: Release Draft
      uses: crs-k/release-draft@v0.6.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
