name: Create a release version
on:
    workflow_dispatch:
        inputs:
            version_increment:
                description: 'Version increment (major, minor, patch)'
                type: choice
                required: true
                default: 'patch'
                options:
                    - major
                    - minor
                    - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.version_increment }}
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}



    #   - name: "Increment Version"
    #     id: version
    #     run: |
    #       current_version=$(git describe --tags --abbrev=0)
    #       curl https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver -o semver
    #       new_version=$(semver bump ${{ github.event.inputs.version_increment }} $current_version)
    #       echo "OLD_GITVER=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
    #       echo "NEW_GITVER=$new_version" >> $GITHUB_OUTPUT


