name: Create a release
on:
    workflow_dispatch:
        inputs:
    pull_request:
        types: [closed]
        branches:
            - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fail if there is a MAJOR and MINOR label
        if: contains(github.event.pull_request.labels.*.name, 'MAJOR') && contains(github.event.pull_request.labels.*.name, 'MINOR')
        run: exit 1

##########################################################
#                                                        #
#               Catch PRs with Major label               #
#                                                        #
##########################################################

      - name: Bump version and push tag | MAJOR
        id: tag_version_major
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'MAJOR')
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: major

      - name: Create a GitHub release | MAJOR
        if: contains(github.event.pull_request.labels.*.name, 'MAJOR')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version_major.outputs.new_tag }}
          name: Release ${{ steps.tag_version_major.outputs.new_tag }}
          body: ${{ steps.tag_version_major.outputs.changelog }}

##########################################################
#                                                        #
#               Catch PRs with Minor label               #
#                                                        #
##########################################################

      - name: Bump version and push tag | MINOR
        id: tag_version_minor
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'MINOR')
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor

      - name: Create a GitHub release | MINOR
        if: contains(github.event.pull_request.labels.*.name, 'MINOR')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version_minor.outputs.new_tag }}
          name: Release ${{ steps.tag_version_minor.outputs.new_tag }}
          body: ${{ steps.tag_version_minor.outputs.changelog }}


###################################################################
#                                                                 #
# If PR does not contain major or minor labels then patch release #
#                                                                 #
###################################################################

      - name: Bump version and push tag | PATCH
        id: tag_version_patch
        if: ${{ ! contains(github.event.pull_request.labels.*.name, 'MAJOR') }} && ${{ ! contains(github.event.pull_request.labels.*.name, 'MINOR') }}
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Create a GitHub release | PATCH
        if: ${{ ! contains(github.event.pull_request.labels.*.name, 'MAJOR') }} && ${{ ! contains(github.event.pull_request.labels.*.name, 'MINOR') }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version_patch.outputs.new_tag }}
          name: Release ${{ steps.tag_version_patch.outputs.new_tag }}
          body: ${{ steps.tag_version_patch.outputs.changelog }}

