name: test
on:
    workflow_dispatch:
      inputs:
        test:
          type: choice
          options:
            - "t"
            - "f"
            - "other"


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "true"
        if: ${{ github.event.inputs.test == 't' }}
        run: echo true
      - name: "false"
        if: ${{ github.event.inputs.test == 'f' }}
        run: echo false
      - name: "true-false"
        if: ${{ github.event.inputs.test == 't' }} || ${{ github.event.inputs.test == 'f' }}
        run: echo true-false
        
